### ISSUE TITLE
childNodes replication

### ISSUE THREAD

**Issue by signalwerk** [punktDe/nodereplicator#12]
I have a Node (`vendor.package:Content.Columns.One`) that uses nodereplication (via `vendor.package:Constraint.Replication`). In the node there is one `childNodes` (`column0`). If I create this node I get an invalid node in the other dimension, because the `childNodes` were not created. Do I do something wrong or is that not supported?

config: 

```yaml
# Node
'vendor.package:Content.Columns.One':
  superTypes:
    'Neos.Neos:Content': true
    'vendor.package:Constraint.Replication': true
  childNodes:
    column0:
      type: 'vendor.package:Collection.Content.Column'

# Collection
'vendor.package:Collection.Content.Column':
  superTypes:
    Neos.Neos:ContentCollection: true
    'vendor.package:Constraint.Replication': true
  constraints:
    nodeTypes:
      '*': false
      'vendor.package:Content.Text': true
      'vendor.package:Content.Image': true

# Replication
"vendor.package:Constraint.Replication":
  abstract: true
  options:
    replication:
      structure: true
      content: true
      updateEmptyPropertiesOnly: true
      createHidden: true
```
