### ISSUE TITLE
Exception when using nodreplicator together with ttreeagency/DimensionKeeper

### ISSUE THREAD

**Issue by paavo** [punktDe/nodereplicator#13]
~~Exception when editing the same node multiple times without publishing~~
The problem only exist if you combine DimensionKeeper with nodereplicator.  

**Steps to reproduce**
1. Inline-Edit a Property from a replicated node
2. Inline-Edit the same property again
-> I get "Duplicate entry" Error (Message below)

**Workaround**
1. Inline-Edit a Property from a replicated node
-> Publish the change
2. Inline-Edit the same property again

**Error Message**
```
An exception occurred while executing 'INSERT INTO neos_contentrepository_domain_model_nodedata (persistence_object_identifier, pathhash, path, parentpathhash, parentpath, identifier, sortingindex, removed, dimensionshash, lastmodificationdatetime, lastpublicationdatetime, hiddenbeforedatetime, hiddenafterdatetime, dimensionvalues, properties, nodetype, creationdatetime, hidden, hiddeninindex, accessroles, workspace, contentobjectproxy, movedto) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ... SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ac02ad531d7de8ba7d938e7f0f6aa9f9-user-xxx-a845436a9e8866c9f4' for key 'UNIQ_CE6515692DBEC7578D94001992F8FB01'
```

**Replication Option**
```
'Vendor.Faq:Content.Faq':
  superTypes:
    'Neos.Neos:Content': true
  ...
  options:
    replication:
      structure: true
      content: true
      updateEmptyPropertiesOnly: true
      createHidden: true
```
