### ISSUE TITLE
Can't delete values with `updateEmptyPropertiesOnly`

### ISSUE THREAD

**Issue by signalwerk** [punktDe/nodereplicator#14]
Imagine I have in two dimensions content:

## Dimension DE
title: "Title DE"

## Dimension FR
title: "Title FR"

I have `updateEmptyPropertiesOnly` set to `true`

```yaml
  options:
    replication:
      structure: true
      content: true
      updateEmptyPropertiesOnly: true
      createHidden: true
```

Now I would like to delete the content of the field in both dimensions.

Since I only expect an update in the other dimension if the other dimension is empty (and not the current) I would think these steps should delete the content:

* go to DE-Dimension
* delete title (in FR-Dimension is still the text)

But now instead of 

## Dimension DE
title: ""

## Dimension FR
title: "Title FR"

I get

## Dimension DE
title: "Title FR"

## Dimension FR
title: "Title FR"

Basically, `updateEmptyPropertiesOnly` is not aware of my current dimension. I would assume the content I enter (even if it's an empty string) is the master and gets copied to the other dimension (or not if not empty) but with an empty value, it happens the other way around.
