### ISSUE TITLE
Restructure und simplify configuration

### ISSUE THREAD

**Issue by daniellienert** [punktDe/nodereplicator#21]
```yaml
'Vendor.Package:Address':
  superTypes:
    'Neos.Neos:Content': true
  
...
  
  options:
    replication:
      structure:
        // Replicate the node itself into the other dimension if the parent exists and the node is missing, default: false
        create: true
        // Create the node as hidden, default: false
        createHidden: true
        // Also delete the node in other dimensions, default: false
        remove: true

      // Defaults for all properties of this nodeType 
      properties:
        update: true // default: false
        updateEmptyOnly: true // default: false

   properties:
     myProperty:
       replication:
         // default: inherited from node level config
         update: false
         // default: inherited from node level config
         updateEmptyOnly: false
```

**Comment by paavo** [comment]
*How to only replicate structure and not the content?*
Exclude every single property?

Configuration before:
```
  options:
    replication:
      structure: true
      content: false
```

Configuration new:
```
  options:
    replication:
      // Replicate the node itself into the other dimension if the parent exists and the node is missing
      replicateCreate: true

   properties:
     myProperty / myProperty2 / myProperty3:
       replication:
         // Exclude for replication, default: false
         excluded: false
```
